In [16]:
import pandas as pd
df = pd.read_excel('dados_star_schema_pratica.xlsx')
df['data'] = pd.to_datetime(df['data'])
df

   pedido_id       data cliente cidade   produto    categoria  valor
0          1 2024-01-01    João     SP  Notebook  Eletrônicos   3500
1          2 2024-01-02   Maria     RJ     Mouse   Acessórios     80
2          3 2024-01-03   Pedro     MG   Teclado   Acessórios    150
3          4 2024-01-04    João     SP   Monitor  Eletrônicos   1200
4          5 2024-01-05     Ana     SP  Notebook  Eletrônicos   3400
5          6 2024-01-06   Maria     RJ   Headset   Acessórios    200
6          7 2024-01-07  Carlos     BA     Mouse   Acessórios     90
7          8 2024-01-08     Ana     SP   Teclado   Acessórios    180
8          9 2024-01-09   Pedro     MG   Monitor  Eletrônicos   1100
9         10 2024-01-10  Carlos     BA  Notebook  Eletrônicos   3600

In [17]:
dim_cliente = df[['cliente','cidade']].drop_duplicates().reset_index(drop=True)

#chave surrogate

dim_cliente['cliente_id'] = dim_cliente.index + 1

In [18]:
dim_produto = df[['produto','categoria']].drop_duplicates().reset_index(drop=True)

dim_produto['produto_id'] = dim_produto.index + 1

In [19]:
dim_data = df[['data']].drop_duplicates().reset_index(drop=True)

dim_data['data'] = pd.to_datetime(dim_data['data'])

dim_data['ano'] = dim_data['data'].dt.year
dim_data['mes'] = dim_data['data'].dt.month
dim_data['dia'] = dim_data['data'].dt.day

dim_data['data_id'] = dim_data.index + 1

In [20]:
#Tabela fato

fato = df.merge(dim_cliente, on=['cliente','cidade'])\
         .merge(dim_produto, on=['produto','categoria'])\
         .merge(dim_data, on=['data'])

fato = fato[['pedido_id', 'cliente_id', 'produto_id', 'data_id', 'valor']]

fato

   pedido_id  cliente_id  produto_id  data_id  valor
0          1           1           1        1   3500
1          2           2           2        2     80
2          3           3           3        3    150
3          4           1           4        4   1200
4          5           4           1        5   3400
5          6           2           5        6    200
6          7           5           2        7     90
7          8           4           3        8    180
8          9           3           4        9   1100
9         10           5           1       10   3600

In [21]:
dim_cliente

  cliente cidade  cliente_id
0    João     SP           1
1   Maria     RJ           2
2   Pedro     MG           3
3     Ana     SP           4
4  Carlos     BA           5